services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY:-lxxzdrgnl/my-own-blog}:latest
    ports:
      - "3200:3000"
    volumes:
      - ./data:/app/data
    env_file: .env.production
    restart: unless-stopped
